# Generated by Django 6.0 on 2026-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='t_sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
