# Generated by Django 6.0 on 2026-01-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_muallif_t_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='t_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
